server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bookly?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

documentation:
  swagger:
    ui-url: "http://localhost:8080/swagger-ui/index.html"
    api-docs-url: "http://localhost:8080/v3/api-docs"
